const remoteMode = location.pathname !== "/" && location.pathname !== "/index.html";
const deckRoot = remoteMode ? location.pathname.replace(/\/+$/, "") : "";
const state = { token: remoteMode ? "" : (sessionStorage.getItem("duck-operator-token") || ""), csrf: "", loginCsrf: "", data: null };
const $ = (selector, root = document) => root.querySelector(selector); const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]); }
function apiPath(path) { return remoteMode ? `${deckRoot}${path}` : path; }
async function api(path, options = {}) { const response = await fetch(apiPath(path), { ...options, credentials: "same-origin", headers: { ...(!remoteMode ? { Authorization: `Bearer ${state.token}` } : {}), ...(remoteMode && options.method && options.method !== "GET" ? { "X-Duck-Operator-CSRF": state.csrf } : {}), ...(options.body ? { "Content-Type": "application/json" } : {}), ...options.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) { if (remoteMode && response.status === 401) showLock(); throw new Error(body.error || `Request failed (${response.status})`); } return body; }
function showLock() { state.csrf = ""; state.data = null; $("[data-app]").hidden = true; $("[data-lock]").hidden = false; }
function notice(message, error = false) { const box = $("[data-notice]"); box.textContent = message; box.classList.toggle("error", error); box.hidden = false; clearTimeout(notice.timer); notice.timer = setTimeout(() => { box.hidden = true; }, 5000); }
function duration(seconds) { const days = Math.floor(seconds / 86400); const hours = Math.floor((seconds % 86400) / 3600); const minutes = Math.floor((seconds % 3600) / 60); return days ? `${days}d ${hours}h` : hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function localDate(value) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Not set" : date.toLocaleString(); }
function values(form) { const input = Object.fromEntries(new FormData(form)); for (const key of ["startsAt", "endsAt", "expiresAt"]) if (input[key]) input[key] = new Date(input[key]).toISOString(); else delete input[key]; return input; }
async function action(input) { return api("/api/action", { method: "POST", body: JSON.stringify(input) }); }
function render() {
  const { guilds, clusters, operator, service, database } = state.data;
  $("[data-metric-guilds]").textContent = guilds.length.toLocaleString(); $("[data-metric-clusters]").textContent = clusters.length; $("[data-metric-memory]").textContent = `${service.memoryMb} MB`; $("[data-metric-uptime]").textContent = duration(service.uptimeSeconds); $("[data-db-count]").textContent = database.guildProfiles.toLocaleString(); $("[data-last-updated]").textContent = `Updated ${new Date().toLocaleTimeString()}`;
  const query = $("[data-server-search]").value.trim().toLowerCase(); const shown = guilds.filter((guild) => !query || guild.id.includes(query) || guild.name.toLowerCase().includes(query)); $("[data-server-rows]").innerHTML = shown.map((guild) => `<tr><td><b>${escapeHtml(guild.name)}</b></td><td><code>${guild.id}</code></td><td>${guild.members.toLocaleString()}</td><td>${guild.cluster.id}</td><td><span class="status ${guild.cluster.status}"><i></i>${guild.cluster.statusLabel}</span></td></tr>`).join("") || `<tr><td colspan="5">No matching servers.</td></tr>`;
  $("[data-cluster-grid]").innerHTML = clusters.map((cluster) => `<article class="cluster-card"><header><strong>${cluster.id}</strong><span class="status ${cluster.status}"><i></i>${cluster.statusLabel}</span></header><small>${cluster.serverCount} servers · ${duration(cluster.uptimeSeconds)} uptime</small></article>`).join("");
  for (const select of $$('[data-cluster-select]')) { const selected = select.value; select.innerHTML = clusters.map((cluster) => `<option value="${cluster.id}">${cluster.id} · ${cluster.statusLabel}</option>`).join(""); if ([...select.options].some((option) => option.value === selected)) select.value = selected; }
  $("[data-maintenance-list]").innerHTML = operator.maintenance.slice(0, 12).map((item) => `<div class="stack-item"><div><b>${item.clusterId}</b><small>${localDate(item.startsAt)} → ${localDate(item.endsAt)}</small></div><span>${item.completedAt ? "Complete" : new Date(item.startsAt) > new Date() ? "Scheduled" : "Active"}</span></div>`).join("") || "<p>No maintenance windows.</p>";
  $("[data-block-list]").innerHTML = Object.entries(operator.blockedUsers).map(([id, item]) => `<div class="stack-item"><div><b>${id}</b><small>${escapeHtml(item.reason)} · ${localDate(item.createdAt)}</small></div><button data-unblock="${id}">Unblock</button></div>`).join("") || "<p>No blocked users.</p>";
  const banner = operator.websiteBanner; $("[data-banner-preview]").innerHTML = banner ? `<b>${escapeHtml(banner.message)}</b><p>${escapeHtml(banner.tone)} · ${localDate(banner.startsAt)}${banner.endsAt ? ` until ${localDate(banner.endsAt)}` : ""}</p>` : "No banner configured.";
  $("[data-audit-list]").innerHTML = operator.auditLog.map((entry) => `<article class="audit-entry"><small>${localDate(entry.at)}</small><code>${escapeHtml(entry.action)}</code><span>${escapeHtml(entry.details?.target || "Duck")}</span></article>`).join("") || "<p>No operator actions yet.</p>";
}
async function refresh() { const button = $("[data-refresh]"); button.disabled = true; try { state.data = await api("/api/overview"); render(); } finally { button.disabled = false; } }
async function unlock(token) { token = String(token || "").trim(); if (remoteMode) { if (!state.loginCsrf) { const status = await api("/api/session"); state.loginCsrf = status.loginCsrf || ""; } const result = await api("/api/session", { method: "POST", headers: { "X-Duck-CSRF": state.loginCsrf }, body: JSON.stringify({ token }) }); state.csrf = result.csrf; state.loginCsrf = ""; } else { state.token = token; sessionStorage.setItem("duck-operator-token", token); } await refresh(); $("[data-lock]").hidden = true; $("[data-app]").hidden = false; }
$("[data-login]").addEventListener("submit", async (event) => { event.preventDefault(); const error = $("[data-login-error]"); error.textContent = ""; try { await unlock(new FormData(event.currentTarget).get("token")); event.currentTarget.reset(); } catch (reason) { error.textContent = reason.message; } });
$("[data-lock-button]").addEventListener("click", async () => { try { if (remoteMode && state.csrf) await api("/api/session", { method: "DELETE" }); } catch { /* Lock locally even if the network request fails. */ } sessionStorage.removeItem("duck-operator-token"); state.token = ""; showLock(); }); $("[data-refresh]").addEventListener("click", () => refresh().catch((error) => notice(error.message, true))); $("[data-server-search]").addEventListener("input", render);
for (const form of $$(".action-form")) form.addEventListener("submit", async (event) => { event.preventDefault(); const button = $("button", form); button.disabled = true; try { await action({ action: form.dataset.action, ...values(form) }); notice("Change applied and recorded in the operator audit."); await refresh(); if (!form.classList.contains("destructive")) form.reset(); } catch (error) { notice(error.message, true); } finally { button.disabled = false; } });
document.addEventListener("click", async (event) => { const unblock = event.target.closest("[data-unblock]"); const simple = event.target.closest("[data-simple-action]"); if (!unblock && !simple) return; const button = unblock || simple; button.disabled = true; try { await action(unblock ? { action: "platform.unblock", userId: unblock.dataset.unblock } : { action: simple.dataset.simpleAction }); notice("Change applied."); await refresh(); } catch (error) { notice(error.message, true); } finally { button.disabled = false; } });
$("[data-inspect]").addEventListener("submit", async (event) => { event.preventDefault(); try { const id = new FormData(event.currentTarget).get("guildId"); const result = await api(`/api/database/guilds/${encodeURIComponent(id)}`); $("[data-database-output]").textContent = JSON.stringify(result.settings, null, 2); } catch (error) { notice(error.message, true); } });
$("[data-export]").addEventListener("click", async () => { try { const snapshot = await api("/api/database/export"); const url = URL.createObjectURL(new Blob([JSON.stringify(snapshot, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `duck-safe-snapshot-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); } catch (error) { notice(error.message, true); } });
for (const link of $$("aside nav a")) link.addEventListener("click", () => { for (const item of $$("aside nav a")) item.classList.toggle("active", item === link); });
async function bootstrap() { if (!remoteMode) { $("[data-lock-copy]").textContent = "This console is available only from this machine. Enter the separate operator token to continue."; $("[data-security-title]").textContent = "Loopback locked"; $("[data-security-copy]").textContent = "127.0.0.1 only"; if (state.token) await unlock(state.token); return; } const status = await api("/api/session"); if (status.authenticated) { state.csrf = status.csrf; await refresh(); $("[data-lock]").hidden = true; $("[data-app]").hidden = false; } else state.loginCsrf = status.loginCsrf || ""; }
bootstrap().catch(() => { sessionStorage.removeItem("duck-operator-token"); state.token = ""; showLock(); });
